#!/usr/bin/python3
import sys

def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <=n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


def get_factors(n):
    for i in range(2, n//2+1):
        if n % i == 0 and is_prime(i) and is_prime(n//i):
            return (i, n//i)
    return None


if __name__ == "__main__":
    filename = sys.argv[1]
    with open(filename, "r") as file:
        for line in file:
            n = int(line.strip())
            factors = get_factors(n)
            if factors is not None:
                p, q = factors
                print(f"{n}={p}*{q}")
            else:
                print(f"unable to find prime factor of {n}")

